// Learn more https://docs.expo.dev/guides/customizing-metro
import { getDefaultConfig } from "expo/metro-config.js";

/** @type {import('expo/metro-config').MetroConfig} */
const config = getDefaultConfig(import.meta.dirname);

// Allow importing .sql migration files generated by drizzle-kit
config.resolver.sourceExts.push("sql");

export default config;
