import sanitizeHtml from "sanitize-html";

const IFRAME_DOMAIN_ALLOWLIST = [
  "bandcamp.com",
  "cdn.embedly.com",
  "dailymotion.com",
  "framatube.org",
  "open.spotify.com",
  "player.bilibili.com",
  "player.twitch.tv",
  "player.vimeo.com",
  "soundcloud.com",
  "vk.com",
  "w.soundcloud.com",
  "youtube-nocookie.com",
  "youtube.com",
];

const VALID_URI_SCHEMES = ["https", "http", "mailto", "tel"];

const ALLOWED_TAGS_AND_ATTRIBUTES: Record<string, string[]> = {
  a: ["href", "title", "id"],
  abbr: ["title"],
  acronym: ["title"],
  aside: [],
  audio: ["src"],
  blockquote: [],
  b: [],
  br: [],
  caption: [],
  cite: [],
  code: [],
  dd: ["id"],
  del: [],
  dfn: [],
  dl: ["id"],
  dt: ["id"],
  em: [],
  figcaption: [],
  figure: [],
  h1: ["id"],
  h2: ["id"],
  h3: ["id"],
  h4: ["id"],
  h5: ["id"],
  h6: ["id"],
  hr: [],
  i: [],
  iframe: ["width", "height", "frameborder", "src", "allowfullscreen"],
  img: [
    "alt",
    "title",
    "src",
    "srcset",
    "sizes",
    "width",
    "height",
    "fetchpriority",
    "decoding",
  ],
  ins: [],
  kbd: [],
  li: ["id"],
  ol: ["id"],
  p: [],
  picture: [],
  pre: [],
  q: ["cite"],
  rp: [],
  rt: [],
  rtc: [],
  ruby: [],
  s: [],
  small: [],
  samp: [],
  source: ["src", "type", "srcset", "sizes", "media"],
  strong: [],
  sub: [],
  sup: ["id"],
  table: [],
  td: ["rowspan", "colspan"],
  tfoot: [],
  th: ["rowspan", "colspan"],
  thead: [],
  time: ["datetime"],
  tr: [],
  u: [],
  ul: ["id"],
  var: [],
  video: ["poster", "height", "width", "src"],
  wbr: [],
  // MathML
  annotation: [],
  "annotation-xml": [],
  maction: [],
  math: ["xmlns"],
  merror: [],
  mfrac: [],
  mi: [],
  mmultiscripts: [],
  mn: [],
  mo: [],
  mover: [],
  mpadded: [],
  mphantom: [],
  mprescripts: [],
  mroot: [],
  mrow: [],
  ms: [],
  mspace: [],
  msqrt: [],
  mstyle: [],
  msub: [],
  msubsup: [],
  msup: [],
  mtable: [],
  mtd: [],
  mtext: [],
  mtr: [],
  munder: [],
  munderover: [],
  semantics: [],
};

const allowedTags = Object.keys(ALLOWED_TAGS_AND_ATTRIBUTES);

const allowedAttributes: Record<string, string[]> = {};
for (const [tag, attrs] of Object.entries(ALLOWED_TAGS_AND_ATTRIBUTES)) {
  if (attrs.length > 0) {
    allowedAttributes[tag] = attrs;
  }
}

export function sanitizeArticleHtml(html: string): string {
  if (!html) return "";

  return sanitizeHtml(html, {
    allowedTags,
    allowedAttributes,
    allowedSchemes: VALID_URI_SCHEMES,
    allowedSchemesAppliedToAttributes: ["href", "src", "cite", "poster"],
    allowedIframeHostnames: IFRAME_DOMAIN_ALLOWLIST,
  });
}
